services:
  app:
    image: app:latest
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -cx "python manage.py migrate &&
              python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - "pgdb"
    volumes:
      - "./src:/app"
    environment:
      DATABASE_URL: postgres://db_user:db_passwd@pgdb/db_name
    ports:
      - "8000:8000/tcp"

  pgdb:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: db_passwd
      POSTGRES_USER: db_user
      POSTGRES_DB: db_name
